stages:
  - test

variables:
  HOST: 127.0.0.1
  PORT: 3000

test:
  image: python:3.9-alpine
  stage: test
  parallel:
    matrix:
      - TEST_SCRIPT:
          - nagios-examples/test_ram_check.py
        TEST_RESULT:
          - 100%
      - TEST_SCRIPT:
          - nagios-examples/test_ram_check_85.py
        TEST_RESULT:
          - 25%
      - TEST_SCRIPT:
          - nagios-examples/test_ram_check_critical.py
        TEST_RESULT:
          - 0%
  script:
    - python agent.py -host $HOST -p $PORT $TEST_SCRIPT &
    - sleep 5  # wait for server to boot up
    - python tests/test_client.py > result.out
    - if [ "$(cat result.out)" = "$TEST_RESULT" ]; then exit 0; else exit 1"; fi
